name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci --omit=dev

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E3055E3745954D17A7370CC3C64558CF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9125A37620114790A91F5CB81342BB29 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4FEE6B8F11244C43A300672464053BBB }}

      - name: Deploy backend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: "it-helpdesk"
          slot-name: "Production"
          package: ./backend
